    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    arm_controller:
        type: position_controllers/JointTrajectoryController
        joints:
          - shoulder_pan_joint
          - shoulder_lift_joint
          - elbow_joint
          - wrist_1_joint
          - wrist_2_joint
          - wrist_3_joint
        constraints:
            goal_time: 2.0
        state_publish_rate: 100

    gripper_controller:
        type: position_controllers/JointTrajectoryController
        joints:
            - gripper_finger1_joint
        state_publish_rate: 25

    joint_position_controller:
        type: ur5_robotiq_85_simulation/JointPositionController
        arm_id: arm
        joint_names:
          - shoulder_pan_joint
          - shoulder_lift_joint
          - elbow_joint
          - wrist_1_joint
          - wrist_2_joint
          - wrist_3_joint
        gains: [
            1, 1, 1, 1, 1, 1
        ]

        